### PR TITLE
fix(Mission Runner): allow for overwriting active mech on synced pilot

### LINKED ISSUE #1605: [BUG] Mission Runner using Vault Synced Pilots is broken
<strong>Submitted At: </strong> 8/9/2021 13:01:06<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When using pilots from my players synced through Vault import in a mission, loading the first encounter throws a number of errors. <br><br><strong>Reproduction Steps:<br> </strong> As a player user, create a pilot and mech. Share your vault record id with the GM User. As the GM user, import the player via Vault import. Navigate to Mission Runner, select a Mission you have created with at least one encounter. Add the pilot and begin the mission<br><br><strong>Expected Result:<br> </strong> You can see the details of all the mechs in the encounter, and do things like adjust stats and end turns.<br><br><strong>Additional Context:<br> </strong> For the GM user, the synced pilots appear to have no active mech, even though the players have set active mechs. The GM can choose a mech when adding them to the mission, but on a reload, the players are back to having no active mech and then the mission view is completely blank.<br><br><br><strong>Stack Trace: </strong> ```
Vue error at [e]
TypeError: Cannot read property 'ID' of null
    at https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:209510
    at Array.find (<anonymous>)
    at a.selected (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:209483)
    at un.get (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:26610)
    at un.evaluate (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:27760)
    at a.selected (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:29669)
    at https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:150302
    at a.ge [as _l] (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:15925)
    at a.dr (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:343:150198)
    at a._render (https://compcon.app/app.bundle.js?__WB_REVISION__=d691e82577381b30bb2b:22:35296)```<br>

### PR DESCRIPTION
**Pull request by TranslucentSabre**
Closes #1605

# Description

This adds a new field field to the ActiveState class and extends the "SyncIgnore" behavior from the Pilot class to provide a way for users who have synced another pilot to set a local active mech. This local active mech is ignored if the active mech is set and published by the owner of the pilot at a later date. 
This is useful to GM users who need an active mech on their player characters for the mission runner.

## Issue Number
`#1605`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by TranslucentSabre** [comment]
Most of the changes are just regex replacements. I will comment on individual important lines.

@jarena3 , may I please get some feedback on the feasibility of this change?

File: src/classes/mech/ActiveState.ts [hunk 1]
```diff
@@ -57,6 +58,7 @@ interface IActiveStateData {
 }
 
 class ActiveState {
+  public readonly SyncIgnore: string[] = ['remoteMech']
```
Comment (TranslucentSabre) [inline src/classes/mech/ActiveState.ts:61]: Add the remoteMech to the list of fields to ignore.

File: src/classes/mech/ActiveState.ts [hunk 2]
```diff
@@ -369,40 +373,44 @@ class ActiveState {
...
+    if (this._pilot.IsLocallyOwned) {
+      this.ActiveMech = mech
+    } else {
+      this._remoteMech = mech
+    }
   }
 
   public get ActiveMech(): Mech | null {
-    return this._mech || null
+    return this._mech != null ? this._mech : this._remoteMech
```
Comment (TranslucentSabre) [inline src/classes/mech/ActiveState.ts:413]: We only use the remoteMech if the original mech field is unset.

File: src/classes/mech/ActiveState.ts [hunk 3]
```diff
@@ -168,13 +172,13 @@ class ActiveState {
   }
 
   public get Move(): number {
-    if (this._pilot_mounted && this._mech.IsShutDown) return 0
-    return !this._pilot_mounted ? this._pilot_move : this._mech.CurrentMove
+    if (this._pilot_mounted && this.ActiveMech.IsShutDown) return 0
```
Comment (TranslucentSabre) [inline src/classes/mech/ActiveState.ts:175]: Please see the comment on the ActiveMech function for more information about these replacements.
https://github.com/massif-press/compcon/pull/1612/files#diff-5cb08f43fba64fa933f78e6c6f184d521ded9bb7f065946391e9ab4ff4ac9b12R413

File: src/classes/pilot/Pilot.ts [hunk 4]
```diff
@@ -1221,15 +1221,16 @@ class Pilot implements ICloudSyncable {
     }
   }
 
-  public Update(data: IPilotData, ignoreProps?: boolean): void {
-    if (ignoreProps) {
+  public Update(data: IPilotData, sync?: boolean): void {
+    if (sync) {
```
Comment (TranslucentSabre) [inline src/classes/pilot/Pilot.ts:1225]: Turn the old "ignoreProps" parameter into a new "sync" parameter. This was only set when performing a could sync right now anyway.

File: src/classes/mech/ActiveState.ts [hunk 5]
```diff
@@ -1164,24 +1173,36 @@ class ActiveState {
...
-    s._bracedCooldown = data.bracedCooldown
-    s._redundant = data.redundant
-    s._pilot_mounted = data.mounted
-    s._stats = data.stats ? data.stats : ActiveState.NewCombatStats()
-    s._deployed = data.deployed ? data.deployed.map(x => Deployable.Deserialize(x, s._mech)) : []
+    s.Update(pilot, data)
     return s
   }
+
+  public Update(pilot: Pilot, data: IActiveStateData, sync?: boolean): void {
```
Comment (TranslucentSabre) [inline src/classes/mech/ActiveState.ts:1181]: A new ActiveState function was needed to update an ActiveState object in place for syncs.

File: src/classes/mech/ActiveState.ts [hunk 6]
```diff
@@ -369,40 +373,44 @@ class ActiveState {
...
+    this.ActiveMech.Repair()
   }
 
   public set ActiveMech(mech: Mech | null) {
-    this._mech = mech
+    if (this._pilot.IsLocallyOwned) {
+      this.ActiveMech = mech
+    } else {
+      this._remoteMech = mech
+    }
```
Comment (TranslucentSabre) [inline src/classes/mech/ActiveState.ts:409]: There is a sed bug here, but this is the place where we differentiate based on locally owned status

Comment (TranslucentSabre) [reply src/classes/mech/ActiveState.ts:409]: The bug is gone now
