### PR TITLE
fix(Active Mode): limited uses initialize to correct maximum

### LINKED ISSUE #1708: [BUG] Limited systems displaying additional uses (12/9)
<strong>Submitted At: </strong> 10/8/2021 18:16:06<br><br><strong>Issue: </strong><br> In active combat mode, Limited systems are displayed with uses beyond the cap (12/9 uses remaining). Not entirely clear why.<br><br><strong>Massif Reference: </strong> <br>

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description
This change retools how Max Uses and Total Limited Uses are calculated and presented in Active mode
to ensure that a mech has the correct number of limited uses at the start of a mission.  It changes
the logic behind Max Use Override so that bonuses must be manually included in the override. Lastly,
this includes a couple of other minor changes that polish some of the Limited Systems behaviors in
Active Mode.

## Issue Number
Closes #1708

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/classes/Statblock.ts [hunk 1]
```diff
@@ -244,7 +244,7 @@ class Statblock {
 [ SYSTEMS ]
   ${mechLoadout.Systems.map(sys => {
     let out = sys.TrueName
-    if (sys.IsLimited) out += ` x${sys.MaxUses + mech.LimitedBonus}`
+    if (sys.IsLimited) out += ` x${sys.getTotalUses(mech.LimitedBonus)}`
```
Comment (msprijatelj) [inline src/classes/Statblock.ts:247]: Brings statblocks in line with how max uses are calculated elsewhere.

File: src/classes/mech/MechEquipment.ts [hunk 2]
```diff
@@ -61,8 +61,10 @@ abstract class MechEquipment extends LicensedItem {
       this.IsOrdnance = data.tags.some(x => x.id === 'tg_ordnance')
       this.CanSetDamage = data.tags.some(x => x.id === 'tg_set_damage_type')
       this.CanSetUses = data.tags.some(x => x.id === 'tg_set_max_uses')
+      this.max_use_override = this.CanSetUses ? 0 : null
     } else {
       this._max_uses = 0
+      this.max_use_override = null
```
Comment (msprijatelj) [inline src/classes/mech/MechEquipment.ts:67]: If max uses can be overridden, set the override to 0 by default (and distinguish between `null` and 0).  Assume that any equipment that has the `tg_set_max_uses` will ultimately require manual input (e.g. Prototype Weapon rolling for uses), and won't need a default (please check me on this, not sure if this should always be the case).

File: src/features/pilot_management/Print/MechPrint.vue [hunk 3]
```diff
@@ -258,7 +258,7 @@
           <v-spacer />
           <span v-if="w.Uses">
             <v-icon
-              v-for="n in w.MaxUses + mech.Pilot.LimitedBonus"
+              v-for="n in w.getTotalUses(mech.Pilot.LimitedBonus)"
```
Comment (msprijatelj) [inline src/features/pilot_management/Print/MechPrint.vue:261]: Whenever we can, we should use the built-in `getTotalUses` over `+` operations when calculating Total Limited Uses.

File: src/ui/components/CCItemUses.vue [hunk 4]
```diff
@@ -44,7 +44,7 @@ export default class CCItemUses extends Vue {
     return this.item.getTotalUses(this.bonus)
   }
   get current(): number {
-    return this.max - this.item.MissingUses
+    return this.item.Uses
```
Comment (msprijatelj) [inline src/ui/components/CCItemUses.vue:47]: Uses is set to the correct maximum already upon Full Repair; trust that it's accurate and use the getter directly.

File: src/ui/components/panels/loadout/active_loadout/CCCombatDialog.vue [hunk 5]
```diff
@@ -121,7 +121,7 @@ export default Vue.extend({
         this.displayLog = this.action.AnyUsed
         // eslint-disable-next-line @typescript-eslint/no-this-alias
         const self = this
-        this.$emit('use')
+        this.$emit('use', free)
```
Comment (msprijatelj) [inline src/ui/components/panels/loadout/active_loadout/CCCombatDialog.vue:124]: This was previously a broken link in the "use" emitter chain; `free` will now continue to bubble up correctly.
