### PR TITLE
fix(Pilot Sheet): show Overpower Caliber and other bonuses in the com…

### LINKED ISSUE #1483: [BUG] Overpower Caliber Not Indicated On Non Compact Mech Summary
<strong>Submitted At: </strong> 6/14/2021 1:14:04<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When a statblock is generated where one of the mounts has overpowered caliber attached, this is indicated on the compact/build summary but not on the default expanded version. It will simply list the weapon attached to the mount with no other indication.<br><br><strong>Reproduction Steps:<br> </strong> Make a mech with one mount that has overpower caliber attached. Open pilot stat block and select that mech. <br><br><strong>Expected Result:<br> </strong> An indication that a mount has overpower caliber on it.<br><br><strong>Additional Context:<br> </strong> <br><br><br><strong>Stack Trace: </strong> <br>

### PR DESCRIPTION
**Pull request by TranslucentSabre**
…pact statblock

Closes #1483

# Description

Update generation of the standard pilot statblock to display weapon mount bonuses just as the compact statblock.

## Issue Number
`#1483`

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/classes/Statblock.ts [hunk 1]
```diff
@@ -143,6 +143,11 @@ class Statblock {
               if (idx + 1 < mount.Weapons.length) output += ' / '
             })
           }
+
+          if (mount.Bonuses.length > 0) {
+            output += ' // ' + mount.Bonuses.map(bonus => bonus.Name).join(', ')
+          }
```
Comment (TranslucentSabre) [inline src/classes/Statblock.ts:149]: This code is taken from line 238 in this same file for the compact statblock.

**Review by jarena3 — APPROVED** [review]
