### PR TITLE
fix(Pilot Sheet): pilot imports ungrouped, immediately visible

### LINKED ISSUE #1650: [BUG] pilots from vault and cloud imports not being added to pilot roster
<strong>Submitted At: </strong> 8/28/2021 15:30:54<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> when trying to import a pilot from a vault or cloud code if the pilot being imported is in a folder/group in the original players compcon then the imported pilot will not show up in the pilot roster until compcon is refreshed at which point it will appear under the same folder it was in for the player that created it<br><br><strong>Reproduction Steps:<br> </strong> 1) on account A create a folder/group and add a pilot to it
2) on account B import the pilot created in step 1
3) the pilot probably wont appear in account B's comp/con
4) refresh the comp/con on account B. the pilot should now appear under it's original folder<br><br><strong>Expected Result:<br> </strong> the expected behavior was for the imported pilot to appear in the pilot roster without the need for a refresh (either ungrouped or under a new folder)<br><br><strong>Additional Context:<br> </strong> *) the group/folder the pilot was imported from did not exist for the one importing it so this bug might not appear if the same folder/group appears in both accounts
*) the bug occurs both for vault and cloud imports
*) i have personally encountered this bug and have also seen it happen to someone else (both times the pilot did not appear in the roster until comp/con was refreshed)<br><br><br><strong>Stack Trace: </strong> <br>

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description
This PR refines #1647 such that newly-imported pilots ~~import their group with them, and~~ are immediately visible. This PR also makes pilot sorting/reindexing more robust.  Finally, this PR changes the default display state for new groups to "visible", ~~and adds more detail to the Import Pilot message to include Pilot Group~~.

EDIT: Updated such that ~~newly-created and~~ imported pilots do NOT import their group, and are instead Ungrouped.  Removed Pilot Group from Import Pilot message.  Keeping the sorting/reindexing and the default display states, as I think they meaningfully add to the project.

EDIT 2: Moved the "ungrouping" to pilot imports only, so that cloned pilots retain the group of their original pilot (a feature that I feel will be more convenient than always sending a "new" pilot to Ungrouped).  Completely new pilots lack a group in the first place, so this changes nothing for them.

## Issue Number
Closes #1650

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/features/pilot_management/Roster/components/add_panels/ImportDialog.vue [hunk 1]
```diff
@@ -23,10 +23,12 @@
       </v-card-actions>
       <v-card-actions v-else-if="pilot">
         <span class="white--text flavor-text">
-          Import
+          Import pilot
           <b>{{ pilot.Callsign.toUpperCase() }}</b>
           //
           <b>{{ pilot.Name }}</b>
+          to group 
+          <b>{{ pilot.Group ? pilot.Group : 'Ungrouped' }}</b>
```
Comment (msprijatelj) [inline src/features/pilot_management/Roster/components/add_panels/ImportDialog.vue:31]: Add a little more detail about the group the Pilot will import into.

File: src/features/pilot_management/Roster/index.vue [hunk 2]
```diff
@@ -171,7 +171,7 @@ export default Vue.extend({
     drag: false,
     newGroupMenu: false,
     tempGroups: [],
-    shown: [],
+    hidden: [],
```
Comment (msprijatelj) [inline src/features/pilot_management/Roster/index.vue:174]: Flipping from `shown` to `hidden` so that newly-imported pilots & their groups are immediately visible, without needing to push the pilot to "shown".

File: src/features/pilot_management/store/index.ts [hunk 3]
```diff
@@ -10,6 +10,21 @@ async function savePilots(pilots: Pilot[]) {
...
+  }
+  pilots.sort((a, b) => {
+    return cmp(pilotGroups.indexOf(a.Group), pilotGroups.indexOf(b.Group)) || cmp(a.SortIndex, b.SortIndex)
+  })
+}
+
+function reindexPilots(pilots: Pilot[]) {
+  pilots.forEach((p, i) => p.SortIndex = i)
+}
+
```
Comment (msprijatelj) [inline src/features/pilot_management/store/index.ts:27]: Move some commonly-used helper functions outside of the Mutations/Actions.

File: src/features/pilot_management/store/index.ts [hunk 4]
```diff
@@ -44,20 +59,16 @@ export class PilotManagementStore extends VuexModule {
...
-      return cmp(this.PilotGroups.indexOf(a.Group), this.PilotGroups.indexOf(b.Group)) || cmp(a.SortIndex, b.SortIndex)
-    })
-    this.Pilots.forEach((p, i) => p.SortIndex = i)
+    sortPilotsByGroup(this.Pilots, this.PilotGroups)
+    reindexPilots(this.Pilots)
   }
 
   @Mutation
   private [ADD_PILOT](payload: Pilot): void {
+    payload.SortIndex = this.Pilots.length
```
Comment (msprijatelj) [inline src/features/pilot_management/store/index.ts:68]: This index isn't permanent; it's simply to position the pilot at the "end" of the `Pilots` array for sorting purposes.

File: src/features/pilot_management/store/index.ts [hunk 5]
```diff
@@ -104,12 +118,17 @@ export class PilotManagementStore extends VuexModule {
 
   @Mutation
   private [DELETE_GROUP](payload: string): void {
-    this.Pilots.forEach((p: Pilot) => {
-      if (p.Group === payload) p.Group = ''
+    this.Pilots.forEach((p: Pilot, i) => {
+      if (p.Group === payload) {
+        p.Group = ''
+        p.SortIndex = this.Pilots.length + i
```
Comment (msprijatelj) [inline src/features/pilot_management/store/index.ts:124]: This sort index is qualitative; as long as relative order is preserved, the sort/reindex below will clean up the group deletion properly, and deposit the newly-groupless pilots in their original order at the end of the "Ungrouped" group.

File: src/features/pilot_management/store/index.ts [hunk 6]
```diff
@@ -165,6 +184,7 @@ export class PilotManagementStore extends VuexModule {
 
   @Action
   public addPilot(payload: { pilot: Pilot; update: boolean }): void {
+    this.context.commit(ADD_GROUP, payload.pilot.Group)
```
Comment (msprijatelj) [inline src/features/pilot_management/store/index.ts:187]: This is the major piece that will fix #1650: Simply making sure the group is appended to PilotGroups prior to adding the Pilot themselves (and subsequently sorting/reindexing as appropriate).

**Comment by msprijatelj** [comment]
Once bitten, twice shy, so please feel free to QA this change before approval/merging.  I believe I covered my bases for displaying imported pilots immediately, but verification is always appreciated.

**Comment by TranslucentSabre** [comment]
I personally don't think it is very user-friendly to import the group along with the pilot from the vault.
As a GM, I will want to group my players pilots together regardless of which group each of them have selected for their own characters.

**Comment by msprijatelj** [comment]
> 
> 
> I personally don't think it is very user-friendly to import the group along with the pilot from the vault.
> As a GM, I will want to group my players pilots together regardless of which group each of them have selected for their own characters.

You know what, I completely agree.  Removed the Pilot Group import by setting a new pilot's group to `''` and fixed the import message to match.  Keeping the rest of the changes for now; I think they'll make the code more maintainable.
