### PR TITLE
fix(Pilot Sheet): LL0 Pilots can select bonus skill triggers

### LINKED ISSUE #1600: [BUG] Skill Point reserve
<strong>Submitted At: </strong>8/6/2021 16:08:23
<strong>Platform: </strong>
Browser - Chrome
<strong>Describe the bug: </strong>
When adding a skill point reserve to a license level 0 character, it adds the skill points but does not allow them to be spent (issue not present in higher level characters) additionally when adding skill point reserve to any level character it grants 2 skill points instead of 1 (allowing a +2 trigger to jump to +6) 
<strong>To Reproduce: </strong>
Enter character's narrative profile and add skill point reserve.
<strong>Expected behavior: </strong>
Will grant 2 skill points instead of 1 and if character is license level 0 will not be able to spend skill points
<strong>Additional context: </strong>

<strong>Contact Info: </strong>
266331477380169728
<strong>Stack Trace: </strong>

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description

This change modifies the logic checking if a pilot can add a skill trigger so that LL0 pilots with extra skill points can select additional talents.  In addition, it modifies the approach to protecting from custom added triggers to simply use `Pilot.CanAddSkill()`, differing from the original fix in #1582.

## Issue Number
Closes #1600

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/classes/pilot/Pilot.ts [hunk 1]
```diff
@@ -575,14 +575,13 @@ class Pilot implements ICloudSyncable {
...
-      const pSkill = this._skills.find(x => x.Skill.ID === skill.ID)
-      return underLimit && pSkill && pSkill.Rank < Rules.MaxTriggerRank
-    }
+    const hasMinSkills = this._skills.length >= Rules.MinimumPilotSkills
+    return this.IsMissingSkills && (
+      !this.has('Skill', skill.ID) || (
+        hasMinSkills && 
+        this._skills.find(x => x.Skill.ID === skill.ID).Rank < Rules.MaxTriggerRank
+      )
+    )
```
Comment (msprijatelj) [inline src/classes/pilot/Pilot.ts:584]: Tried to reduce some of the boolean/if/elses here to boil the statement down into a single boolean.  Originally extracted `!this.has('Skill', skill.ID)` and `this._skills.find(x => x.Skill.ID === skill.ID).Rank < Rules.MaxTriggerRank` to external `const`s, but moved the calculations to deeper in the boolean in an effort to save a small amount processing time.

I admit I'm working off of Python knowledge here, where if a boolean terminates early (e.g. if `this.IsMissingSkills` evaluates to `false`, cutting off everything after the `&&`).  If that doesn't hold true in Typescript (or is ultimately negligible), I'd prefer to extract the calculations into well-named external `const`s for clarity's sake.

Comment (jarena3) [reply src/classes/pilot/Pilot.ts:584]: You're correct here, it'll bail as soon as hasMinSkills resolves to `false` (or null or undefined)
