### PR TITLE
fix(Mech Sheet): add tooltips to the Mech Sheet Nav bar buttons

### LINKED ISSUE #1597: [BUG] Missing Tooltips in Active Mech Sheet Menu
<strong>Submitted At: </strong> 8/6/2021 3:26:45<br><br><strong>Browser: </strong> Chrome<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> In the Active Mech Sheet, the menu bar along the bottom-right of the screen is missing tooltips for the following buttons and icons: "Mech Configuration", Person, Power, Gearwheel, Boxes+. <br><br><strong>Reproduction Steps:<br> </strong> I tested this error on a fresh pilot to be sure. Here is that, but you can probably skip this paragraph:
Open compcon.app/#/ in incognito mode (for a fresh load). Click Pilot Roster, then Add New Pilot. Click Create New Pilot. Enter a Name and Callsign (tested with "A" and "A") then click Select Character Template. Select a Template (tested with Vanguard) and Continue. Register the New Pilot.

The Original Error:
Click on your pilot in the Pilot Roster. At the bottom of the screen, click on the Mech Icon in a menu bar (its tooltip should read "Active Mech Sheet"). 

You should be on a new screen. There is a menu bar in the lower right corner. Hover your mouse cursor over the following buttons for at least 5 seconds each: "Mech Configuration", "Combat Analytics", Person Icon, Power icon, gear icon, and boxes+ icon. <br><br><strong>Expected Result:<br> </strong> No tooltip will display for any of these buttons except for "Combat Analytics", where the tooltip reads "Feature in Development." <br><br><strong>Additional Context:<br> </strong> A QoL fix. Not essential, but gave me some confusion when navigating these menus.<br><br><br><strong>Stack Trace: </strong> <br>

### PR DESCRIPTION
**Pull request by Macrophaje**
Closes #1597

# Description

Added tooltip text to the mech sheet nav buttons that was missing. 

## Issue Number
`#1597`

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue [hunk 1]
```diff
@@ -3,18 +3,24 @@
     <div id="cap" />
     <div v-if="$vuetify.breakpoint.mdAndUp" class="d-inline">
       <cc-nav-item tile depressed :selected="selected === 0" @click="$emit('set-page', 0)">
-        MECH CONFIGURATION
+        <cc-tooltip inlinde delayed content="Active Mech Configuration">
+          MECH CONFIGURATION
+        </cc-tooltip>
```
Comment (TranslucentSabre) [inline src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue:8]: This is nitpicky and I know it, but for consistency sake can you wrap the cc-nav-item in the cc-tooltip as well?
This is how it is laid out for "COMBAT ANALYTICS" on line 10.

File: src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue [hunk 2]
```diff
@@ -3,18 +3,24 @@
...
       <cc-tooltip simple inline content="Feature In Development">
         <cc-nav-item disabled :selected="selected === 1" @click="$emit('set-page', 1)">
           COMBAT ANALYTICS
         </cc-nav-item>
       </cc-tooltip>
       <v-btn icon fab x-small outlined class="mx-4 unskew" dark @click="toPilotSheet()">
-        <v-icon large>cci-pilot</v-icon>
+        <cc-tooltip inline delayed content="Player Profile">
+          <v-icon large>cci-pilot</v-icon>
+        </cc-tooltip>
```
Comment (TranslucentSabre) [inline src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue:18]: I don't know if we might want to also wrap the whole button in the cc-tooltip for these last ones or not. Does the UX feel any different if you do change the nesting?

**Review by TranslucentSabre — COMMENTED** [review]
Overall I like it, and I think that it is functional as it is.

File: src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue (hunk 1 above)
Comment (Macrophaje) [reply src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue:8]: Yup, I can do that. I was basing my changes off PlayerNav.vue, which does it differently, but I can nest it outside for consistency in the file.

File: src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue (hunk 2 above)
Comment (Macrophaje) [reply src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue:18]: Yeah I can wrap the tool tip around the v-btn with no ill effects. I'll make that change.

File: src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue [hunk 3]
```diff
@@ -42,7 +48,9 @@
     <v-menu offset-y top>
       <template v-slot:activator="{ on: menu }">
         <v-btn class="unskew ml-2" icon dark v-on="menu">
-          <v-icon>mdi-settings</v-icon>
+          <cc-tooltip inline delayed content="Mech Options">
```
Comment (Macrophaje) [inline src/features/pilot_management/PilotSheet/sections/mech/components/MechNav.vue:51]: Conversely, I did find that I can't move the cc-tooltip element any higher for the two menu buttons, as it causes the menu to render in the upper left corner of the screen when you click the button.

**Review by TranslucentSabre — APPROVED** [review]

**Comment by TranslucentSabre** [comment]
Looks good to me, but @jarena3 has final say.

**Review by jarena3 — APPROVED** [review]
