### PR TITLE
fix(Pilot Sheet): constrain license level edit to 0-12

### LINKED ISSUE #1826: [BUG] Negative LLs possible
<strong>Submitted At: </strong> 1/19/2022 12:18:53<br><br><strong>Browser: </strong> Firefox<br><strong>Platform: </strong> Desktop<br><br><strong>Issue Description: </strong><br> When clicking "Edit License Level", when at LL0, it is possible to reduce LL to negative values.<br><br><strong>Reproduction Steps:<br> </strong> 1. Create a new pilot.
2. Navigate to the new pilot's pilot sheet.  They should be LL0.
3. Click on the "Edit License Level" button next to "License Level" on the pilot sheet.
4. In the resulting dialog box, reduce the LL by 1 and click "Set Pilot Level".
5. Observe that the pilot is now registered with LL -1.
6. Repeat steps 3 and 4. Observe that this can drive a Pilot's LL lower and lower.<br><br><strong>Expected Result:<br> </strong> LL can go no lower than 0; the tick box that can edit LL can only cover the rules-legal levels of 0 to 12.<br><br><strong>Additional Context:<br> </strong> Instead of reducing the LL by 1, try to reduce by 2 or more. Click "Set Pilot Level". Observe that the LL resets to 0, as normally expected.

Beyond this, I'd recommend using a dropdown menu instead of an editable input box with upticking or downticking.  This would prevent any malformed inputs and more strongly define the legal license levels.<br><br><br> **Contact Info:**<br/>Valkyrion#6196<br>

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description
This change modifies the "Edit License Level" dialog to restrict license level selection to 0-12 via a `v-select` dropdown menu.  It also refines some of the style on the page to prevent confusion over which fields are able to be modified.

## Issue Number
Closes #1826

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by msprijatelj** [comment]
Example screenshots from Windows 10 using Firefox browser:

Example after just opening the edit dialog:
image

Example of the dropdown menu:
image

Post-selection:
image

File: src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue [hunk 1]
```diff
@@ -20,35 +20,33 @@
...
+            style="display:inline-block"
             class="level-input"
-          />
+          >
+            {{ pilot.Level }}
+          </span>
         </v-col>
 
         <v-col cols="auto" class="mx-3">
+          <span class="overline"></span>
```
Comment (msprijatelj) [inline src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue:32]: This is literally just a placeholder to center the arrow between Current and New level.

File: src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue [hunk 2]
```diff
@@ -20,35 +20,33 @@
...
           <span class="overline">New Level:</span>
           <br />
-          <v-text-field
+          <v-select
             v-model="newLevel"
+            :items="levels"
             type="number"
-            maxlength="2"
             hide-details
+            hide-spin-buttons
```
Comment (msprijatelj) [inline src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue:45]: This was a built-in option for hiding Spin Buttons; it seemed reasonable to use a builtin instead of a custom style.

File: src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue [hunk 3]
```diff
@@ -115,15 +106,20 @@ export default Vue.extend({
...
+.level-input .v-select__selection {
   font-size: 55px;
   width: 90px !important;
   height: 65px !important;
-  max-height: 65px !important;
+  line-height: 65px !important;
+}
+
+.level-input input {
+  display: none;
```
Comment (msprijatelj) [inline src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue:122]: The `v-select` object had an "input" field that competed for space with the "selection" (though text input isn't available), causing the selection to overflow out of the `v-select` object.  Hiding this seemed to be the most reasonable solution, but if this will cause other issues (e.g. on mobile) then please let me know a preferred alternative.

File: src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue [hunk 4]
```diff
@@ -133,9 +129,9 @@ export default Vue.extend({
   text-align: center !important;
 }
 
-.level-input input::-webkit-outer-spin-button,
-.level-input input::-webkit-inner-spin-button {
-  -webkit-appearance: none;
-  margin: 0;
+.level-input .v-input__append-inner {
+  align-self: center !important;
+  margin: 0 !important;
```
Comment (msprijatelj) [inline src/features/pilot_management/PilotSheet/components/LevelEditDialog.vue:134]: This styles the dropdown arrow on the `v-select` dropdown.

**Review by msprijatelj — COMMENTED** [review]
A few comments to elucidate what I'm doing here.

**Review by jarena3 — APPROVED** [review]
