### PR TITLE
fix(pilot): use Pilot as MechSkillController.Parent

### LINKED ISSUE #2070: [BUG] Mech skill point reserve not granting bonus
Description
When adding the "MECH SKILL POINT" reserve it does not grant a bonus skill point to the pilot

To Reproduce
1. Go to add reserves and bonuses
2. Add MECH SKILL POINT

Expected behavior
+1 mech skill point.

 - Browser: chrome,

### PR DESCRIPTION
**Pull request by msprijatelj**
# Description
This PR changes the Parent type for MechSkillController to be `Pilot` like the other controllers. It also allows LL0 characters to benefit from `mech_skill_point` bonuses, as there was a previous check for the `Level` property that short-circuited the MaxHASEPoints bonus calculation.

It is unclear why the parent type was previously `IHASEContainer`; if clarification could be provided as to why the Parent type should *stay* `IHASEContainer`, we can come up with an alternative solution that checks for a `null` or `undefined` value of `Level` instead of simply a false-y one (since `0` would be treated the same as `null` or `undefined` in the context of 2.3.9a's MaxHASEPoints method).

## Issue Number
Closes #2070

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

File: src/classes/components/mechskills/MechSkillsController.ts [hunk 1]
```diff
@@ -48,9 +48,7 @@ class MechSkillsController {
 
   //TODO: requires target change as part of bonus rework
   public get MaxHASEPoints(): number {
-    const p = this.Parent as any
-    if (!p.Level) return Rules.MinimumMechSkills
```
Comment (msprijatelj) [inline src/classes/components/mechskills/MechSkillsController.ts:52]: If we decide that `this.Parent` should *stay* as type `IHASEContainer`, we will just need to modify this line so that `0` is accounted for appropriately, whether that be checking for a `number` type, or for whether p.Level is `undefined` or `null`, or even simply just performing the `Bonus.Int()` function without `p.Level` included.

**Review by jarena3 — APPROVED** [review]

File: src/classes/components/mechskills/MechSkillsController.ts (hunk 1 above)
Comment (jarena3) [reply src/classes/components/mechskills/MechSkillsController.ts:52]: I think this is a good change -- NPCs *might* implement IHASEContainer in the upcoming GM rebuild but I haven't totally settled on it yet, but as you've pointed out it's pretty easy to address this when the time comes
